# Generated by Django 4.1.5 on 2023-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_teammatesearch_hackathon_name_teammatesearch_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatesearch',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='email3',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='github2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='github3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='name2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='name3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='phone2',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='phone3',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
