# Generated by Django 4.1.5 on 2023-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_alter_teammatesearch_email2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatesearch',
            name='team',
            field=models.CharField(default='team', max_length=255),
        ),
    ]
