# Generated by Django 4.1.5 on 2023-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0006_teammatesearch_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatesearch',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
