# Generated by Django 4.1.5 on 2023-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_teammatesearch_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatesearch',
            name='github1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='github2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammatesearch',
            name='github3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
