# Generated by Django 4.1.5 on 2023-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0009_team_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='userid_githubser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('github_username', models.CharField(max_length=255)),
            ],
        ),
    ]
