# Generated by Django 4.1.5 on 2023-04-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0010_userid_githubser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userid_githubser',
            new_name='userid_githubuser',
        ),
    ]
