# Generated by Django 4.1.5 on 2023-04-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0011_rename_userid_githubser_userid_githubuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid_githubuser',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
