# Generated by Django 4.1.5 on 2023-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0012_userid_githubuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_requests',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
